modLoader="javafml" #mandatory
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] #mandatory
modId="netherupdateplus" #mandatory
version="1.0" #mandatory
displayName="NetherUpdatePlus" #mandatory
logoFile="netherUpdatePlus_icon.png" #optional
credits="for Mr. Mint for his great textures" #optional
authors="Bretzelfresser and Mr. Mint" #optional
description='''
extends the nether
'''
[[dependencies.netherupdateplus]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.netherupdateplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
